import { readFileSync, writeFileSync } from "node:fs";

import { SAT_DATES } from "../src/data/test-dates";

type SheetRow = {
  country: "EG" | "SA";
  name: string;
  city: string;
  address: string;
  code: string;
  avail: [string, string, string];
  link: string;
};

const rows: SheetRow[] = JSON.parse(readFileSync("scripts/sheet-data.json", "utf8"));
const cache: Record<string, { lat: number; lng: number } | null> = JSON.parse(
  readFileSync("scripts/coords-cache.json", "utf8")
);

const q = (v: string) => JSON.stringify(v);

const missingCoords: string[] = [];

const centerLines: string[] = [];
const coordLines: string[] = [];
const availLines: string[] = [];

for (const row of rows) {
  const coords = cache[row.link];
  if (!coords) {
    missingCoords.push(`${row.code} ${row.name}`);
    continue;
  }

  centerLines.push(
    `  { code: ${q(row.code)}, name: ${q(row.name)}, address: ${q(row.address)}, country: ${q(
      row.country === "EG" ? "eg" : "sa"
    )}, city: ${q(row.city)}, link: ${q(row.link)} },`
  );

  coordLines.push(
    `  ${q(row.code)}: { lat: ${coords.lat}, lng: ${coords.lng} },`
  );

  const perDate: string[] = [];
  row.avail.forEach((status, i) => {
    const date = SAT_DATES[i];
    const seats = status === "غير متاح" ? 0 : 1;
    perDate.push(`    ${q(date)}: ${seats}`);
  });
  availLines.push(`  ${q(row.code)}: {\n${perDate.join(",\n")}\n  },`);
}

const src = `// Generated by scripts/build-data-files.ts — do not edit by hand.
// Source: user-provided Excel (scripts/sheet-data.json) + resolved Google Maps links (scripts/coords-cache.json).

export type TestCenterCountry = "eg" | "sa";

export interface TestCenterSeed {
  code: string;
  name: string;
  address: string;
  country: TestCenterCountry;
  city?: string;
  link: string;
}

export const TEST_CENTERS: TestCenterSeed[] = [
${centerLines.join("\n")}
];
`;

const coords = `// Generated by scripts/build-data-files.ts — precise coordinates from Google Maps links.
export const TEST_CENTER_COORDINATES: Record<string, { lat: number; lng: number }> = {
${coordLines.join("\n")}
};
`;

const avail = `// Generated by scripts/build-data-files.ts — per-date availability from the Excel sheet.
// 0 = غير متاح, 1 = متاح (mirrors the sheet exactly; no seat counts are invented).
export const TEST_AVAILABILITY: Record<string, Record<string, number>> = {
${availLines.join("\n")}
};
`;

writeFileSync("src/data/test-centers.ts", src, "utf8");
writeFileSync("src/data/test-center-coordinates.ts", coords, "utf8");
writeFileSync("src/data/test-availability.ts", avail, "utf8");

console.log(`centers written: ${centerLines.length}`);
console.log(`missing coords: ${missingCoords.length}`, missingCoords.slice(0, 5));