import "dotenv/config";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { TEST_CENTERS } from "../src/data/test-centers";

interface NominatimPlace {
  lat: string;
  lon: string;
  display_name: string;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const AREA_FALLBACKS: Array<{ keywords: string[]; query: string }> = [
  { keywords: ["sheikh zayed"], query: "Sheikh Zayed City, Giza, Egypt" },
  { keywords: ["shorouk", "shrouk", "sherouk"], query: "El Shorouk, Cairo, Egypt" },
  { keywords: ["obour", "qaliobia"], query: "Obour City, Cairo, Egypt" },
  { keywords: ["helioopolis", "heliopolis"], query: "Heliopolis, Cairo, Egypt" },
  { keywords: ["zamalek"], query: "Zamalek, Cairo, Egypt" },
  { keywords: ["maadi"], query: "Maadi, Cairo, Egypt" },
  { keywords: ["nasr city"], query: "Nasr City, Cairo, Egypt" },
  { keywords: ["tagamoe", "tagamoa", "new cairo", "katameya", "el katameya", "5th settlement", "fifth settlement"], query: "New Cairo, Cairo, Egypt" },
  { keywords: ["new capital", "new administrative capital"], query: "New Administrative Capital, Egypt" },
  { keywords: ["6th of october", "sixth of october", "6 october", "hadayek october"], query: "6th of October City, Giza, Egypt" },
  { keywords: ["dream land"], query: "Dream Land, 6th of October City, Giza, Egypt" },
  { keywords: ["shebin", "shebin al-koum", "shebeen"], query: "Shebin El Koum, Monufia, Egypt" },
  { keywords: ["haram", "mansouria"], query: "Al Haram, Giza, Egypt" },
  { keywords: ["benha", "banha", "qalyubiya", "qalyubia"], query: "Banha, Qalyubia, Egypt" },
  { keywords: ["mansoura", "talkha"], query: "Mansoura, Dakahlia, Egypt" },
  { keywords: ["damietta"], query: "New Damietta, Egypt" },
  { keywords: ["port said"], query: "Port Said, Egypt" },
  { keywords: ["luxor", "el toud"], query: "Luxor, Egypt" },
  { keywords: ["hurghada"], query: "Hurghada, Red Sea, Egypt" },
  { keywords: ["assiut", "asyut"], query: "Assiut, Egypt" },
  { keywords: ["abis", "abees", "abeys", "abeise"], query: "Abis, Alexandria, Egypt" },
  { keywords: ["alexandria", "nozha airport", "smouha", "miami", "janaklees"], query: "Alexandria, Egypt" },
  { keywords: ["maryotia", "mariotia", "maryout"], query: "Al Maryotia, Giza, Egypt" },
  { keywords: ["giza"], query: "Giza, Egypt" },
  { keywords: ["cairo"], query: "Cairo, Egypt" },
];

function areaFallback(address: string): string | undefined {
  const lower = address.toLowerCase();
  for (const { keywords, query } of AREA_FALLBACKS) {
    if (keywords.some((keyword) => lower.includes(keyword))) return query;
  }
  return undefined;
}

async function geocode(query: string): Promise<NominatimPlace | null> {
  const url =
    `https://nominatim.openstreetmap.org/search` +
    `?format=jsonv2&limit=1&countrycodes=eg&q=${encodeURIComponent(query)}`;

  try {
    const response = await fetch(url, {
      headers: {
        "Accept-Language": "en",
        "User-Agent": "TestCenterFinder/1.0 (educational project)",
      },
    });
    if (!response.ok) return null;
    const places = (await response.json()) as NominatimPlace[];
    return places[0] ?? null;
  } catch {
    return null;
  }
}

async function geocodeOne(address: string): Promise<{ place: NominatimPlace | null; via: "exact" | "area" | "none" }> {
  const exact = await geocode(`${address}, Egypt`);
  if (exact) return { place: exact, via: "exact" };

  const fallback = areaFallback(address);
  if (fallback) {
    const area = await geocode(fallback);
    if (area) return { place: area, via: "area" };
  }

  return { place: null, via: "none" };
}

async function main() {
  const outFile = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../src/data/test-center-coordinates.ts"
  );

  const rows: string[] = [];
  let ok = 0;
  let skipped = 0;

  for (const [index, center] of TEST_CENTERS.entries()) {
    const { place, via } = await geocodeOne(center.address);
    if (place) {
      rows.push(
        `  "${center.code}": { lat: ${Number.parseFloat(place.lat)}, lng: ${Number.parseFloat(place.lon)} },`
      );
      ok += 1;
      console.log(
        `[${index + 1}/${TEST_CENTERS.length}] ✓ (${via}) ${center.code} ${center.name} — ${place.display_name}`
      );
    } else {
      skipped += 1;
      console.log(`[${index + 1}/${TEST_CENTERS.length}] ✗ ${center.code} ${center.name} — NOT FOUND`);
    }
    await sleep(1100);
  }

  const content = `/**
 * Coordinates (lat / lng) for each test center, keyed by center code.
 *
 * This file is generated by \`npm run geocode\` (Nominatim / OpenStreetMap).
 * Entries marked with area-level precision (city / district) can be refined
 * by hand or by providing exact GPS coordinates.
 */
export const TEST_CENTER_COORDINATES: Record<string, { lat: number; lng: number }> = {
${rows.join("\n")}
};
`;

  writeFileSync(outFile, content, "utf8");
  console.log(`\nDone. ${ok} geocoded, ${skipped} skipped. Wrote ${outFile}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});